---
root: true
parser: '@typescript-eslint/parser'
extends:
  - eslint:recommended
  - prettier

env:
  es6: true
  browser: false
  node: true
  jasmine: false
  jest: false

parserOptions:
  ecmaVersion: 2022
  sourceType: module

rules:
  max-len:
    - error
    - code: 200
      ignoreComments: true
      ignoreTrailingComments: true
      ignoreStrings: true
      ignoreTemplateLiterals: true
      ignoreRegExpLiterals: true

  newline-before-return: off
  quotes: [warn, single]
  object-curly-spacing: [error, never]
  no-use-before-define:
    - error
    - functions: false
      classes: false
  template-curly-spacing: [error, never]
  curly: [error, all]
  no-unused-vars: 1
